services:
  todo-api:
    build:
      context: ./TodoApi
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "3001:3001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default

  todo-app:
    build:
      context: ./todo-app
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "3000:3000"
    depends_on:
      - todo-api
    networks:
      - default

networks:
  default:
    driver: bridge
